### ISSUE TITLE
{"detail": "Required field algorithm not found"}' using python requests digest-authentication

### ISSUE THREAD

**Issue by guialante** [juanriaza/django-rest-framework-digestauth#2]
Regards

I,m currently using python requests diguest authentication (http://docs.python-requests.org/en/latest/user/authentication/#digest-authentication) to create objects using you Digest Authentication to django-rest-framework, tutorial but when i made request i got this {"detail": "Required field algorithm not found"}', 

the header of the request made by python requests digest-authenticatios is:
{'Accept': '_/_',
 'Accept-Encoding': 'gzip, deflate, compress',
 'Authorization': 'Digest username="jose", realm="django-rest-framework", nonce="a88c699a9c0830dd7707454cc1921e96", uri="/snippets/", response="5ddad2b0e3f51c4cbc6584543709e4dd", opaque="DRFOPAQUE:ocSiYVVmRX9FkFGrcsHscDGHNcQ", qop=auth, nc=00000001, cnonce="d9cdf9ad9765e8a9"',
 'Content-Length': u'28',
 'Content-Type': 'application/x-www-form-urlencoded',
 'User-Agent': 'python-requests/1.1.0 CPython/2.7.3 Darwin/12.2.0'}

here I put some code how im making the request

import requests
from requests.auth import HTTPDigestAuth
url = 'http://127.0.0.1:8000/snippets/'
data = {'code': 'hola mundo desde pyhon'}
r = requests.post(url, auth=HTTPDigestAuth('jose', 'jose'), data=data)

can you help me to solve this 
thank you

**Comment by juanriaza** [comment]
The header lacks of algorithm specification. Are you using the latest version of `python-requests`? It should be fixed with this commit https://github.com/kennethreitz/requests/commit/a6360ca134623a9faecfe64b51e86f42bffb4dd9

**Comment by guialante** [comment]
I can solve the error reinstalling python requests and is working, but now I got: u'{"detail": "Authentication credentials were not provided."}'

the request headers is:
{'Accept': '_/_',
 'Accept-Encoding': 'gzip, deflate, compress',
 'Authorization': 'Digest username="jose", realm="django-rest-framework", nonce="1403ed7d7749f5189afc407ba3d65994", uri="/snippets/", response="a4057af3345667eed7cf3456c16baf06", opaque="DRFOPAQUE:ocSiYVVmRX9FkFGrcsHscDGHNcQ", algorithm="MD5", qop=auth, nc=00000001, cnonce="b2994a7302a0198c"',
 'Content-Length': u'27',
 'Content-Type': 'application/x-www-form-urlencoded',
 'User-Agent': 'python-requests/1.1.0 CPython/2.7.3 Darwin/12.2.0'}

response headers:

{'allow': 'HEAD, GET, POST, OPTIONS',
 'content-type': 'application/json',
 'date': 'Sun, 03 Mar 2013 19:30:52 GMT',
 'server': 'WSGIServer/0.1 Python/2.7.3',
 'vary': 'Accept',
 'www-authenticate': 'Digest realm="django-rest-framework", qop="auth", nonce="8463dec4da17524c18050ed85e2b36bd", opaque="DRFOPAQUE:ocSiYVVmRX9FkFGrcsHscDGHNcQ", algorithm="MD5"'}

and the I made change in django-rest-framework-tutoria views.py and settings.py
https://gist.github.com/guialante/d68199c0ef16409c7a00 --settings.py
https://gist.github.com/guialante/5077804 -- views.py

what do I doing wrong to get this 401 message

thanks you

**Comment by juanriaza** [comment]
@guialante check that you have a user with a username `jose` and with a token (not a password) `jose`.

**Comment by guialante** [comment]
@juanriaza yes the user exists with token, I try to make exactly how I wrote before

import requests
from requests.auth import HTTPDigestAuth
url = 'http://127.0.0.1:8000/snippets/'
data = {'code': 'hola mundo desde pyhon'}
r = requests.post(url, auth=HTTPDigestAuth('jose', 'jose'), data=data)

but I got this 401 message, should I do something extra setup to try to use your digest-authentication ?

**Comment by juanriaza** [comment]
@guialante does it keep failing? Haven't received any other raising concerns about this.
